--------------------------------------------------------------------------------
-- *OBS: A base está na nuvem e suas configurações estão no aplication.properties!!!!
--------------------------------------------------------------------------------

CREATE TABLE [IF NOT EXISTS] colaborador (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cpf varchar(255) NULL,
	dt_nascimento timestamp NULL,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	telefone varchar(255) NULL,
	setor_id int8 NULL,
	CONSTRAINT colaborador_pkey PRIMARY KEY (id),
	CONSTRAINT uk_dluwox59xryije1xr98mqc60n UNIQUE (cpf),
	CONSTRAINT fko5h2cn8it6fgjivvdmgd459fo FOREIGN KEY (setor_id) REFERENCES setores(id)
);


CREATE TABLE setores (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NOT NULL,
	CONSTRAINT setores_pkey PRIMARY KEY (id)
);